name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: write
  contents: read
  checks: write  # Добавлено для создания статус-чеков

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore SpaceBattle.sln

    - name: Check code formatting
      run: dotnet format SpaceBattle.sln --verify-no-changes

    - name: Build
      run: dotnet build SpaceBattle.sln --configuration Release --no-restore

    - name: Test
      run: >
        dotnet test SpaceBattle.sln 
        --configuration Release 
        --no-build 
        --logger "trx;LogFileName=test-results.trx" 
        --collect:"XPlat Code Coverage" 
        --results-directory ./TestResults

    - name: Dotnet Test Reporter
      uses: bibipkins/dotnet-test-reporter@v1.6.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test & Coverage Results'
        results-path: ./TestResults/*.trx
        coverage-path: ./TestResults/**/coverage.cobertura.xml
        coverage-type: cobertura
        coverage-threshold: 90
